/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import His.HisSystem;
import His.Network.Organization.Organization;
import His.UserAccount.UserAccount;
import UserInterface.ModifyAccount.ModifyAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 52909
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */

    private JPanel rightPanel;
    private UserAccount account;
    private Organization organization;
    private HisSystem business;
    public PatientJPanel(JPanel rightPanel, UserAccount account, Organization organization, HisSystem business) {
        initComponents();
        this.rightPanel=rightPanel;
        this.account=account;
        this.business=business;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registeredBTN = new javax.swing.JButton();
        personalCaseBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        registeredBTN.setText(" registered");
        registeredBTN.setPreferredSize(new java.awt.Dimension(300, 100));
        registeredBTN.setRequestFocusEnabled(false);
        registeredBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredBTNActionPerformed(evt);
            }
        });
        add(registeredBTN);

        personalCaseBTN.setText("Personal Case");
        personalCaseBTN.setPreferredSize(new java.awt.Dimension(300, 100));
        personalCaseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalCaseBTNActionPerformed(evt);
            }
        });
        add(personalCaseBTN);

        jButton1.setText("My reservation");
        jButton1.setPreferredSize(new java.awt.Dimension(300, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Modify Password");
        jButton2.setPreferredSize(new java.awt.Dimension(300, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void personalCaseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalCaseBTNActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.rightPanel.getLayout();
        this.rightPanel.add("PersonalCases",new PersonalCase(this.rightPanel,account,this.organization,business));
        layout.next(rightPanel);
    }//GEN-LAST:event_personalCaseBTNActionPerformed

    private void registeredBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredBTNActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.rightPanel.getLayout();
        this.rightPanel.add("RegisteredHos",new RegisteredHos(this.rightPanel,business,account));
        layout.next(rightPanel);
    }//GEN-LAST:event_registeredBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.rightPanel.getLayout();
        this.rightPanel.add("Reservation",new Reservation(this.rightPanel,account,this.organization,business));
        layout.next(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.rightPanel.getLayout();
        this.rightPanel.add("modify",new ModifyAccount(this.account,this.rightPanel));
        layout.next(rightPanel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton personalCaseBTN;
    private javax.swing.JButton registeredBTN;
    // End of variables declaration//GEN-END:variables
}
