/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import His.HisSystem;
import His.Network.Enterprise.Enterprise;
import His.Network.Network;
import His.Network.Organization.Organization;
import His.Network.Role.Patient;
import His.Network.Role.PatientCase;
import His.Network.WorkQueue.MEWork.Medicine;
import His.Network.WorkQueue.MEWork.MedicineStorage;
import His.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52909
 */
public class PersonalCase extends javax.swing.JPanel {

    /**
     * Creates new form PersonalCase
     */
    private JPanel rightPanel;
    private UserAccount account;
    private Organization organization;
    private HisSystem business;
    public PersonalCase(JPanel rightPanel, UserAccount account, Organization organization, HisSystem business) {
        initComponents();
        this.rightPanel=rightPanel;
        this.account=account;
        this.business=business;
        this.organization=organization;
        populate();
    }
    public void populate(){
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();

        model.setRowCount(0);
        
        for (PatientCase Personcase : ((Patient)account.getRole()).getPersonalCase()) {
            if(Personcase.getStatus()==true){
                Object[] row = new Object[3];
                row[0] = Personcase.getCase();
                String med="";
                for(Map.Entry<String, MedicineStorage> entry : Personcase.getMedicine().getMedicineStorageMap().entrySet()){
                    med+=(entry.getValue().getName()+":"+entry.getValue().getCount()+"  ");
                }
                row[1] = med;


                model.addRow(row);
            }
                    
                
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case", "Medicine"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)this.rightPanel.getLayout();
        this.rightPanel.remove(this);
        layout.previous(this.rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
