/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airline.Abstract.User;
import Business.Airline.Company.Airplane;
import Business.Airline.Users.Airliner;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomastakovich
 */
public class AirlinerManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerManagePanel
     */
    private JPanel panelRight;
    private Airliner airliner;
    public AirlinerManagePanel(JPanel panelRight, Airliner airliner) {
        initComponents();
        this.panelRight = panelRight;
        this.airliner = airliner;
        populate();
    }
    
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
        dtm.setRowCount(0);
        for(Airplane a : airliner.getFleet().getAirplane()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = a;
            row[1] = a.getModel();
            row[2] = a.getRow();
            row[3] = a.getColumn();
            row[4] = a.getSerialNumber();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirplane = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboAirAtt = new javax.swing.JComboBox<String>();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnManageFlight = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tblAirplane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacture", "Model", "Row", "Colume", "Serial Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAirplane);
        if (tblAirplane.getColumnModel().getColumnCount() > 0) {
            tblAirplane.getColumnModel().getColumn(0).setResizable(false);
            tblAirplane.getColumnModel().getColumn(1).setResizable(false);
            tblAirplane.getColumnModel().getColumn(2).setResizable(false);
            tblAirplane.getColumnModel().getColumn(3).setResizable(false);
            tblAirplane.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Airplanes you have :");

        btnCreate.setText("Add an Airplane!");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel2.setText("by:");

        comboAirAtt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Manufacture", "Model", "Seats", "Serial Number", "Seats Range" }));
        comboAirAtt.setToolTipText("");
        comboAirAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAirAttActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Seats_Max :");

        jLabel4.setText("Seats_Min :");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnManageFlight.setText("Manage Flights");
        btnManageFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightActionPerformed(evt);
            }
        });

        jButton1.setText("Delete a Airplane");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Airplane");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMax)
                                            .addComponent(txtMin)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnSearch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboAirAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnManageFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnBack))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboAirAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreate)
                        .addGap(12, 12, 12)
                        .addComponent(btnManageFlight)
                        .addGap(3, 3, 3)))
                .addComponent(jButton2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("CreateAirplanePanel",new CreateAirplanePanel(airliner,panelRight));
        layout.next(panelRight);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String input = txtSearch.getText();
        if(comboAirAtt.getSelectedItem().equals(" ")){
            DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
            dtm.setRowCount(0);
            for(Airplane a : airliner.getFleet().getAirplane()){
                
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = a;
                row[1] = a.getModel();
                row[2] = a.getRow();
                row[3] = a.getColumn();
                row[4] = a.getSerialNumber();
                dtm.addRow(row);
                
            }
        }
        if(comboAirAtt.getSelectedItem().equals("Manufacture")){
            DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
            dtm.setRowCount(0);
            for(Airplane a : airliner.getFleet().getAirplane()){
                if(a.equals(input)){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = a;
                    row[1] = a.getModel();
                    row[2] = a.getRow();
                    row[3] = a.getColumn();
                    row[4] = a.getSerialNumber();
                    dtm.addRow(row);
                }
            }
        }
        if(comboAirAtt.getSelectedItem().equals("Seats Range")){
            DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
            dtm.setRowCount(0);
            for(Airplane a : airliner.getFleet().getAirplane()){
                if((a.getColumn()*a.getRow()) <= Integer.parseInt(txtMax.getText()) && (a.getColumn()*a.getRow()) >= Integer.parseInt(txtMin.getText())){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = a;
                    row[1] = a.getModel();
                    row[2] = a.getRow();
                    row[3] = a.getColumn();
                    row[4] = a.getSerialNumber();
                    dtm.addRow(row);
                }
            }
        }
        
        if(comboAirAtt.getSelectedItem().equals("Model")){
            DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
            dtm.setRowCount(0);
            for(Airplane a : airliner.getFleet().getAirplane()){
                if(a.getModel().equals(input)){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = a;
                    row[1] = a.getModel();
                    row[2] = a.getRow();
                    row[3] = a.getColumn();
                    row[4] = a.getSerialNumber();
                    dtm.addRow(row);
                }
            }
        }
        
        try{
            
            if(comboAirAtt.getSelectedItem().equals("Serial Number")){
                DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
                dtm.setRowCount(0);
                for(Airplane a : airliner.getFleet().getAirplane()){
                    if(a.getSerialNumber() == Integer.parseInt(input)){
                        Object[] row = new Object[dtm.getColumnCount()];
                        row[0] = a;
                        row[1] = a.getModel();
                        row[2] = a.getRow();
                        row[3] = a.getColumn();
                        row[4] = a.getSerialNumber();
                        dtm.addRow(row);
                    }
                }
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Serial Number bust be integer!");
        }
        
        
        try{
            
            if(comboAirAtt.getSelectedItem().equals("Seats")){
                DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
                dtm.setRowCount(0);
                for(Airplane a : airliner.getFleet().getAirplane()){
                    int s = a.getColumn()*a.getRow();
                    if(s == Integer.parseInt(txtSearch.getText())){
                        Object[] row = new Object[dtm.getColumnCount()];
                        row[0] = a;
                        row[1] = a.getModel();
                        row[2] = a.getRow();
                        row[3] = a.getColumn();
                        row[4] = a.getSerialNumber();
                        dtm.addRow(row);
                    }
                }
            }
            
        }catch(NumberFormatException s){
            JOptionPane.showMessageDialog(null, "Seats must be integer!");
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.remove(this);
        layout.previous(panelRight);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("FlightManagePanel",new FlightManagePanel(airliner,panelRight));
        layout.next(panelRight);
    }//GEN-LAST:event_btnManageFlightActionPerformed

    private void comboAirAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAirAttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAirAttActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblAirplane.getSelectedRow();
        if(selectedrow < 0) {
            JOptionPane.showMessageDialog(null, "Please  select a row from table first to view details!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Airplane airplane = (Airplane)tblAirplane.getValueAt(selectedrow, 0);
            if(airplane.getFlight()==null)
            {
                airliner.getFleet().deleteAirPlane(airplane);
            }
            else
            {
                if(airplane.isAvailable())
                {
                    airplane.getFlight().getSchedule().setFlight(null);

                    airliner.getFleet().deleteAirPlane(airplane);
                }
                else
                    JOptionPane.showMessageDialog(null, "This airplane is still in mission", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
        populate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int selectedrow = tblAirplane.getSelectedRow();
        if(selectedrow < 0) {
            JOptionPane.showMessageDialog(null, "Please  select a row from table first to view details!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Airplane airliner = (Airplane)tblAirplane.getValueAt(selectedrow, 0);
            CardLayout layout = (CardLayout) panelRight.getLayout();
            panelRight.add("DisplayAirplane",new DisplayAirplane(airliner,panelRight));
            layout.next(panelRight);
        }    
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnManageFlight;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboAirAtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirplane;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
