/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Airline.Company.Flight;
import Business.Airline.Company.FlightSchedule;
import Business.Airline.Company.Ticket;
import Business.Airline.Manage.MasterTravelSchedule;
import Business.Airline.Users.Customer;
import Business.Airline.Users.UserList;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class CustomerOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrderJPanel
     */
    
    private JPanel rightPanel;
    private Customer customer;
    private UserList userlist;
    
  

    public CustomerOrderJPanel(MasterTravelSchedule master, JPanel rightPanel, Customer customer, UserList userlist) {
          initComponents();
         
         this.rightPanel=rightPanel;
         this.customer=customer;
         this.userlist=userlist;
         populate();
                   //To change body of generated methods, choose Tools | Templates.
    }
    public void populate(){
        DefaultTableModel dtms = (DefaultTableModel)ticketTable.getModel();
        dtms.setRowCount(0);
        SimpleDateFormat date=new SimpleDateFormat("YYYY-MM-dd");
        
        /*
        private String airlineNO;
    private String ticketNumber;
    private String airlineAgency;
    private Seat seat;
    private Customer customer;

        */
        for(Ticket a:customer.getTicket()){
            
            Object[] row = new Object[dtms.getColumnCount()];
            row[0]=a;//票号
            row[1]=a.getAirlineNO();//航班号
            row[4]=a.getAirlineAgency();//航空公司
            
            row[2]=a.getCustomer();//客户
            row[5]=a.getSeat().getFlight().getAirplane().getManufacture()+a.getSeat().getFlight().getAirplane().getModel();//飞机型号
            row[3]=a.getSeat().getSeat();
            
            dtms.addRow(row);
            
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Order", "Airline number", "Customer", "Seat", "Airliner", "Airplane Model"
            }
        ));
        jScrollPane1.setViewportView(ticketTable);

        jButton2.setText("View details");

        jButton3.setText("cancel the order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack1)
                            .addComponent(jButton3))))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jButton2)
                .addGap(67, 67, 67)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(btnBack1)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow1 = ticketTable.getSelectedRow();
        
        if(selectedRow1>=0)
        {
            Ticket ticket=(Ticket)ticketTable.getValueAt(selectedRow1, 0);
            ticket.getCustomer().delTicket(ticket);
            userlist.delTicket(ticket);
            ticket.getSeat().getFlight().returnSeat(ticket);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ticketTable;
    // End of variables declaration//GEN-END:variables
}
