/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Airline.Company.Flight;
import Business.Airline.Company.FlightSchedule;
import Business.Airline.Company.Seat;
import Business.Airline.Manage.MasterTravelSchedule;
import Business.Airline.Users.Customer;
import Business.Airline.Users.TravelOffice;
import Business.Airline.Users.UserList;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class CustomerSechduleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSechduleJPanel
     */
    private MasterTravelSchedule master;
    private JPanel rightPanel;
    private Customer customer;
    private ArrayList<Flight> flight;
    private UserList userlist;
    
    public CustomerSechduleJPanel(MasterTravelSchedule master,JPanel rightPanel,Customer customer,UserList userlist) {
        initComponents();
        this.master=master;
        this.rightPanel=rightPanel;
        this.customer=customer;
        this.userlist=userlist;
        jLabel1.setText(customer.getUserName());
        master.update();
        
        flight=new ArrayList<Flight>();
        for(Flight f:master.getFlight())
        {
            flight.add(f);
        }
        populate();
    
    }
    private void initFlight()
    {
        flight.removeAll(flight);
        
    }
    private void sortFlight(String depart,String arrive,String date,String airliner,String airplane){
        initFlight();
        SimpleDateFormat dateFormat=new SimpleDateFormat("YYYY/MM/dd");
        for(Flight f:master.getFlight())
        {
            if((f.getSchedule().getDepart().equals(depart) || depart.equals(""))&&
               (f.getSchedule().getArrive().equals(arrive)||arrive.equals(""))&&
                (dateFormat.format(f.getSchedule().getDate()).equals(date)||date.equals(""))&&
                (airplane.equals(f.getAirplane().getManufacture()+f.getAirplane().getModel())||airplane.equals(""))&&
                (airliner.equals(f.getSchedule().getAgency().getAirline())||airliner.equals(""))
              )
                flight.add(f);
            
            
        }
        populate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSchedule = new javax.swing.JTable();
        btnPurchase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Depart", "Arrive", "Date", "DepartTime", "Flight Number", "Tour Time", "price", "seatNum", "airplane"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSchedule);
        if (tableSchedule.getColumnModel().getColumnCount() > 0) {
            tableSchedule.getColumnModel().getColumn(0).setResizable(false);
            tableSchedule.getColumnModel().getColumn(1).setResizable(false);
            tableSchedule.getColumnModel().getColumn(2).setResizable(false);
            tableSchedule.getColumnModel().getColumn(3).setResizable(false);
            tableSchedule.getColumnModel().getColumn(4).setResizable(false);
            tableSchedule.getColumnModel().getColumn(5).setResizable(false);
            tableSchedule.getColumnModel().getColumn(6).setResizable(false);
            tableSchedule.getColumnModel().getColumn(7).setResizable(false);
            tableSchedule.getColumnModel().getColumn(8).setResizable(false);
            tableSchedule.getColumnModel().getColumn(9).setResizable(false);
        }

        btnPurchase.setText("purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("depart");

        jLabel3.setText("arrive");

        jLabel4.setText("date");

        jLabel5.setText("YYYY/MM/dd");

        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("AirLiner");

        jLabel7.setText("Airplane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPurchase))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addComponent(jButton1)))))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addGap(150, 150, 150)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(btnBack)
                .addGap(78, 78, 78)
                .addComponent(btnPurchase)
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
         CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
          int selectedRow=tableSchedule.getSelectedRow();
          if(selectedRow<0){
          JOptionPane.showMessageDialog(null,"Please select a flight from table","warning",JOptionPane.WARNING_MESSAGE);
          
          
          }else{
             Flight result=(Flight)tableSchedule.getValueAt(selectedRow,0);
             String name=customer.getUserName();
             String flightNo=result.getSchedule().getFlightNo();
             CustomerSeatsJPanel panel=new CustomerSeatsJPanel(result,rightPanel,customer,userlist);
               rightPanel.add("CustomerSeatsJpanel",panel);
               CardLayout layout=(CardLayout) rightPanel.getLayout();
               layout.next(rightPanel); 
                
                /* ViewCarJPanel panel=new ViewCarJPanel(carProcessContainer,result);
                carProcessContainer.add("ViewAccountJPanel",panel);
                CardLayout layout=(CardLayout)carProcessContainer.getLayout();
                layout.next(carProcessContainer);
          */
          
          
          }
        
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.sortFlight(this.jTextField1.getText(), this.jTextField2.getText(), this.jTextField3.getText(),
                this.jTextField4.getText(),this.jTextField5.getText()
        );
    }//GEN-LAST:event_jButton1ActionPerformed
   public void populate(){
        DefaultTableModel dtms = (DefaultTableModel)tableSchedule.getModel();
        dtms.setRowCount(0);
        SimpleDateFormat date=new SimpleDateFormat("YYYY-MM-dd");
        
        for(Flight a:flight){
            
            Object[] row = new Object[dtms.getColumnCount()];
            row[0]=a;
            row[1]=a.getSchedule().getDepart();
            row[2]=a.getSchedule().getArrive();
            
            row[3]=date.format(a.getSchedule().getDate());
            row[4]=a.getSchedule().getDepartTime();
            row[5]=a.getSchedule().getFlightNo();
            row[6]=a.getSchedule().getTourTime();
            row[7]=a.getPrice()[0];
            row[8]=a.getSeatNumber();
            row[9]=a.getAirplane().getManufacture()+a.getAirplane().getModel();
            
            dtms.addRow(row);
            
         }
        }
   
   
   
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tableSchedule;
    // End of variables declaration//GEN-END:variables
}
