/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 52909
 */
public class CreateCar extends javax.swing.JPanel {

    /**
     * Creates new form CreateCar
     */
    private JPanel userPane;
    private CarList carList;
    private int mode;
    private Car car;
    private void viewCar(Car car)
    {
        availableRadio.setSelected(car.isAvailable());
        brandT.setText(car.getBrand());
        cityT.setText(car.getCity());
        
        yearCT.setText(String.valueOf(String.valueOf(car.getMaintenanceCertificate())));
        
        yearMT.setText(String.valueOf(String.valueOf(car.getDateOfManufacture())));
        maxT.setText(String.valueOf(car.getMaxseats()));
        minT.setText(String.valueOf(car.getMinseats()));
        modelT.setText(car.getModel());
        modelNumberT.setText(car.getModelNumber());
        serialT.setText(car.getSerialNumber());
        xT.setText(String.valueOf(car.getX().getX()));
        yT.setText(String.valueOf(car.getX().getY()));
        updateDate.setText(car.getLastUpdate().get2DigitYearStart().toString());
    }
    private void enabled(boolean a)
    {
        if(mode==3)
            jButton1.setEnabled(!a);
        else
            jButton1.setEnabled(true);
        if(mode==2)
        {
            jLabel21.setVisible(true);
            updateDate.setVisible(true);
            
        }
        else
        {
            jLabel21.setVisible(false);
            updateDate.setVisible(false);
        }
        availableRadio.setEnabled(a);
        brandT.setEnabled(a);
        cityT.setEnabled(a);
        
        yearCT.setEnabled(a);
        
        yearMT.setEnabled(a);
        maxT.setEnabled(a);
        minT.setEnabled(a);
        modelT.setEnabled(a);
        modelNumberT.setEnabled(a);
        serialT.setEnabled(a);
        xT.setEnabled(a);
        yT.setEnabled(a);
    }
    public CreateCar(JPanel userPane,CarList carList,Car car,int i) {
        initComponents();
        this.userPane=userPane;
        this.carList=carList;
        if(i==2)
        {
            this.mode=i;
            enabled(false);
            title.setText("ViewDetail");
            jButton2.setVisible(false);
            viewCar(car);
        }
        if(i==3)
        {
            this.mode=i;
            enabled(true);
            viewCar(car);
            title.setText("update");
            jButton2.setVisible(true);
            jButton2.setText("update");
            this.car=car;
        }
    }

    CreateCar(JPanel userPane, CarList carList, int i) {
        initComponents();
        enabled(true);
        this.mode=i;
        title.setText("Create Car");
        jButton2.setVisible(true);
        jButton2.setText("Create");
        this.carList=carList;
        this.userPane=userPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        availableRadio = new javax.swing.JRadioButton();
        yT = new javax.swing.JTextField();
        xT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        minT = new javax.swing.JTextField();
        maxT = new javax.swing.JTextField();
        modelNumberT = new javax.swing.JTextField();
        modelT = new javax.swing.JTextField();
        cityT = new javax.swing.JTextField();
        brandT = new javax.swing.JTextField();
        serialT = new javax.swing.JTextField();
        yearMT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        yearCT = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        updateDate = new javax.swing.JLabel();

        jButton1.setText("<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("available");

        jLabel2.setText("Point");

        jLabel3.setText("Seats");

        jLabel4.setText("ModelNumber");

        jLabel5.setText("Model");

        jLabel6.setText("City");

        jLabel7.setText("Brand");

        jLabel8.setText("Serial");

        jLabel9.setText("ManufactureDate");

        jLabel10.setText("maintenanceCertificate");

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("X");

        jLabel12.setText("Y");

        jLabel13.setText("MIN");

        jLabel14.setText("MAX");

        jLabel15.setText("YYYY");

        jLabel20.setText("YYYY");

        title.setText("Create Pane");

        jLabel21.setText("Updatetime");

        updateDate.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearMT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(yearCT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xT)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel13)
                                    .addComponent(minT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availableRadio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(yT)
                                    .addComponent(maxT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(modelNumberT)
                            .addComponent(modelT)
                            .addComponent(cityT)
                            .addComponent(brandT)
                            .addComponent(serialT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(35, 35, 35)
                        .addComponent(updateDate)
                        .addGap(107, 107, 107))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(availableRadio)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(updateDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(minT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modelNumberT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modelT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(brandT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(serialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yearMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userPane.remove(this);
        CardLayout layout=(CardLayout)userPane.getLayout();
        layout.previous(userPane);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(brandT.getText()==null || brandT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please input the Brand!");
            return;
        }
            
        if(cityT.getText()==null || cityT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please input the City!");
            return;
        }
            
        if(modelT.getText()==null || modelT.getText().equals(""))
        {
        
            JOptionPane.showMessageDialog(null, "Please input the model!");
            return;
        }
        if(modelNumberT.getText()==null || modelNumberT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please input the modelnumber!");
            return;
        }
            
        if(serialT.getText()==null || serialT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please input the serial!");
            return;
                
        }
            
        try{
            Integer.parseInt(yearCT.getText());
            Integer.parseInt(yearMT.getText());
            Integer.parseInt(maxT.getText());
            Integer.parseInt(minT.getText());
            Integer.parseInt(xT.getText());
            Integer.parseInt(yT.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please input all the field");
            return;
        }
        if(mode==1)
        {
            Car car = carList.addCar();
            car.setAvailable(availableRadio.isSelected());
            car.setBrand(brandT.getText());
            car.setCity(cityT.getText());
            car.setDateOfManufacture(Integer.parseInt(yearMT.getText()));
            String pattern1 = "yyyy-MM-dd HH:mm:ssZ";
            car.setLastUpdate(new SimpleDateFormat(pattern1));
            car.setMaintenanceCertificate(Integer.parseInt(yearCT.getText()));
            car.setMaxseats(Integer.parseInt(maxT.getText()));
            car.setMinseats(Integer.parseInt(minT.getText()));
            car.setModel(modelT.getText());
            car.setModelNumber(modelNumberT.getText());
            car.setSerialNumber(serialT.getText());
            car.setX(new Point(Integer.parseInt(xT.getText()), Integer.parseInt(yT.getText())));
            JOptionPane.showMessageDialog(null, "car successfuly creater!");
        }
        if(mode==3)
        {
            
            car.setAvailable(availableRadio.isSelected());
            car.setBrand(brandT.getText());
            
            car.setCity(cityT.getText());
            String pattern = "yyyy-MM-dd";
            String pattern1 = "yyyy-MM-dd HH:mm:ssZ";
            car.setLastUpdate(new SimpleDateFormat(pattern1)) ;
            
            car.setDateOfManufacture(Integer.parseInt(yearMT.getText()));
            
            
            car.setMaintenanceCertificate(Integer.parseInt(yearCT.getText()));
            car.setMaxseats(Integer.parseInt(maxT.getText()));
            car.setMinseats(Integer.parseInt(minT.getText()));
            car.setModel(modelT.getText());
            car.setModelNumber(modelNumberT.getText());
            car.setSerialNumber(serialT.getText());
            car.setX(new Point(Integer.parseInt(xT.getText()), Integer.parseInt(yT.getText())));
            //carList.addCar(car);
            JOptionPane.showMessageDialog(null, "car successfuly update!");
            enabled(false);
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton availableRadio;
    private javax.swing.JTextField brandT;
    private javax.swing.JTextField cityT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maxT;
    private javax.swing.JTextField minT;
    private javax.swing.JTextField modelNumberT;
    private javax.swing.JTextField modelT;
    private javax.swing.JTextField serialT;
    private javax.swing.JLabel title;
    private javax.swing.JLabel updateDate;
    private javax.swing.JTextField xT;
    private javax.swing.JTextField yT;
    private javax.swing.JTextField yearCT;
    private javax.swing.JTextField yearMT;
    // End of variables declaration//GEN-END:variables
}
