/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import Business.CarList;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 52909
 */
public class IndexJPane extends javax.swing.JPanel {

    /**
     * Creates new form IndexJPane
     */
    private JPanel userPane;
    private CarList carList;
    public IndexJPane() {
        initComponents();
        
    }
    
    IndexJPane(JPanel userPane, CarList carList) {
        initComponents();
        this.carList=carList;
        this.userPane=userPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(java.awt.Color.orange);
        setLayout(new java.awt.GridBagLayout());

        jButton1.setText("FindCar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("AddMyCar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setText("ModelList");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DisplayCars pane=new DisplayCars(userPane,carList,1);
        userPane.add("CreateCar",pane);
        CardLayout layout=(CardLayout)userPane.getLayout();
        layout.next(userPane);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CreateCar pane=new CreateCar(userPane,carList,1);
        userPane.add("FindCar",pane);
        CardLayout layout=(CardLayout)userPane.getLayout();
        layout.next(userPane);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ModelList pane=new ModelList(userPane,carList);
        userPane.add("ModelList",pane);
        CardLayout layout=(CardLayout)userPane.getLayout();
        layout.next(userPane);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
