/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52909
 */
public class ManageAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccount
     */
    private JPanel displayJPanel;
    private AccountDirectory accountDirectory;
    public ManageAccount() {
        initComponents();
    }

    ManageAccount(JPanel displayJPanel, AccountDirectory accountDirectory) {
         //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.displayJPanel=displayJPanel;
        this.accountDirectory=accountDirectory;
        populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel dtm=( DefaultTableModel)tableDisplay.getModel();
        dtm.setRowCount(0);
        for(Account ac:accountDirectory.getAccountList())
        {
            Object row[]=new Object[4];
            row[0]=ac;
            row[1]=ac.getRoutingNumber();
            row[2]=ac.getAccountNumber();
            row[3]=ac.getBalance();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDisplay = new javax.swing.JTable();
        searchT = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jButton1.setText("delete account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("view details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Name", "Routing Number", "Account Number", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tableDisplay);

        jButton4.setText("<back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton2))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(searchT, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(searchT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        displayJPanel.remove(this);
        CardLayout layout=(CardLayout)displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableDisplay.getSelectedRow();
        if(selectedrow>=0)
        {
            int a=JOptionPane.YES_NO_CANCEL_OPTION;
            int b=JOptionPane.showConfirmDialog(null, "Would you like to delete the account","WARNING",a);
            if(b==JOptionPane.YES_OPTION)
            {
                Account ac=(Account)tableDisplay.getValueAt(selectedrow, 0);
                accountDirectory.deleteAccount(ac);
                JOptionPane.showMessageDialog(null, "sucessfuly delete");
                populateTable();
            }
           
            
        }
        else
            JOptionPane.showMessageDialog(null, "select a row now");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableDisplay.getSelectedRow();
        if(selectedrow>=0)
        {           
            Account ac=(Account)tableDisplay.getValueAt(selectedrow, 0);
            ViewDetails pane=new ViewDetails(displayJPanel,ac);
            displayJPanel.add("ViewDetails",pane);
            CardLayout layout=(CardLayout)displayJPanel.getLayout();
            layout.next(displayJPanel);
        }
        else
            JOptionPane.showMessageDialog(null, "select a row now");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Account ac=accountDirectory.searchAccount(searchT.getText());
        if(ac==null)
        {
            JOptionPane.showMessageDialog(null, "can not find the answer");
        }
        else
        {
            ViewDetails pane=new ViewDetails(displayJPanel,ac);
            displayJPanel.add("ViewDetails",pane);
            CardLayout layout=(CardLayout)displayJPanel.getLayout();
            layout.next(displayJPanel);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchT;
    private javax.swing.JTable tableDisplay;
    // End of variables declaration//GEN-END:variables
}
