/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Agency;

import Business.Airline.Company.FlightSchedule;
import Business.Airline.Manage.MasterTravelSchedule;
import Business.Airline.Users.Customer;
import Business.Airline.Users.UserList;
import java.awt.CardLayout;
import static java.lang.System.out;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52909
 */
public class FlightSchedulePanel extends javax.swing.JPanel {
    private MasterTravelSchedule master;
    private JPanel rightPanel;
    /**
     * Creates new form FlightSchedule
     */
    public FlightSchedulePanel(MasterTravelSchedule master,JPanel rightPanel) {
        initComponents();
        this.master=master;
        this.rightPanel=rightPanel;
        populate();
    }
    public void populate(){
        DefaultTableModel dtms = (DefaultTableModel)tableSchedule.getModel();
        dtms.setRowCount(0);
        SimpleDateFormat date=new SimpleDateFormat("YYYY-MM-dd");
        master.update();
        for(FlightSchedule a:master.getFlightSchedule()){
            
            Object[] row = new Object[dtms.getColumnCount()];
            row[0]=a;
            row[1]=a.getDepart();
            row[2]=a.getArrive();
            row[3]=date.format(a.getDate());
            row[4]=a.getDepartTime();
            row[5]=a.getFlightNo();
            row[6]=a.getTourTime();
            dtms.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSchedule = new javax.swing.JTable();
        backBTN = new javax.swing.JButton();

        tableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Depart", "Arrive", "Date", "DepartTime", "Flight Number", "Tour Time"
            }
        ));
        jScrollPane1.setViewportView(tableSchedule);

        backBTN.setText("<BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBTN)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        this.rightPanel.remove(this);
        CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_backBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSchedule;
    // End of variables declaration//GEN-END:variables
}
